import type { Metadata } from "next";
import { LegalLayout, Section } from "@/components/legal/LegalLayout";
import { TOS_VERSION, TOS_EFFECTIVE_DATE } from "@/lib/legal/versions";

export const metadata: Metadata = {
  title: "Terms of Service · Drisora",
  description: "Terms of Service governing use of the Drisora pavement intelligence platform.",
};

export default function DrisoraTermsPage() {
  return (
    <LegalLayout title="Terms of Service" version={TOS_VERSION} effectiveDate={TOS_EFFECTIVE_DATE}>
      <p className="text-[#A8A8B6]">
        These Terms of Service (&ldquo;Terms&rdquo;) are a binding agreement between you and{" "}
        <strong className="text-white">[COMPANY LEGAL NAME]</strong> (&ldquo;Drisora&rdquo;,
        &ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo;), operator of the Drisora platform at
        drisora.vercel.app and all related applications, APIs, and services (the
        &ldquo;Service&rdquo;).
      </p>

      <Section heading="1. Acceptance of Terms">
        <p>
          1.1. By creating an account, checking the acceptance box at registration, or otherwise
          accessing or using the Service, you agree to be bound by these Terms and by our Privacy
          Policy, which is incorporated by reference.
        </p>
        <p>
          1.2. If you accept these Terms on behalf of a road agency, municipality, contractor, firm,
          or other entity (an &ldquo;Organization&rdquo;), you represent that you are authorized to
          bind that Organization, and &ldquo;you&rdquo; refers to both you and the Organization.
        </p>
        <p>1.3. If you do not agree, you must not access or use the Service.</p>
      </Section>

      <Section heading="2. Eligibility and Age Restriction (18+)">
        <p>
          2.1. The Service is for professional and business use only. You must be at least{" "}
          <strong className="text-white">eighteen (18) years of age</strong> to register or use the
          Service. This is an absolute requirement with no exceptions.
        </p>
        <p>
          2.2. By registering you represent and warrant that you are 18 or older. We verify date of
          birth at registration and will reject or terminate any account where the user is, or is
          reasonably believed to be, under 18.
        </p>
        <p>
          2.3. You further warrant that you access the Service in a professional capacity (e.g., as a
          road-agency officer, municipal official, contractor, civil engineer, surveyor, or
          authorized researcher) and not as a consumer.
        </p>
      </Section>

      <Section heading="3. Description of the Service">
        <p>
          3.1. Drisora ingests drone-captured imagery of roadways, applies automated machine-learning
          models to detect and classify pavement distresses, and produces analytical outputs
          including Pavement Condition Index (&ldquo;PCI&rdquo;) scores, distress maps, and reports.
        </p>
        <p>
          3.2. The Service is a decision-support and analytical tool only. It is not a certified
          engineering survey, a statutory road-safety audit, or a substitute for professional
          engineering judgment.
        </p>
      </Section>

      <Section heading="4. AI Output Disclaimer (Advisory Only)">
        <p>
          4.1. <strong className="text-white">All outputs generated by the Service</strong> &mdash;
          including distress classifications, severity ratings, PCI scores, measurements,
          geolocations, and reports &mdash; are produced by automated, probabilistic AI/ML systems
          and are <strong className="text-white">advisory and indicative only</strong>.
        </p>
        <p>
          4.2. Outputs may contain errors, omissions, false positives, false negatives, or
          inaccuracies arising from image quality, lighting, weather, occlusion, drone altitude,
          sensor calibration, model limitations, or other factors.
        </p>
        <p>
          4.3. Drisora outputs <strong className="text-white">do not constitute a certified
          engineering assessment</strong>, a professional opinion, or a guarantee of pavement
          condition, safety, or fitness for any purpose. Any decision affecting public safety,
          structural integrity, budgeting, maintenance prioritization, contracting, or regulatory
          compliance must be independently reviewed, verified, and approved by a qualified, licensed
          civil/pavement engineer exercising their own professional judgment.
        </p>
        <p>4.4. You assume full responsibility for any reliance on, or decision made using, the outputs.</p>
      </Section>

      <Section heading="5. Drone Imagery, DGCA Compliance, and Lawful Acquisition">
        <p>
          5.1. <strong className="text-white">DGCA and regulatory compliance.</strong> You represent,
          warrant, and covenant that all imagery, video, and associated data you upload or process was
          captured in full compliance with all applicable laws, including without limitation: (a) the
          Drone Rules, 2021 and amendments, issued by the DGCA and the Ministry of Civil Aviation,
          Government of India; (b) Digital Sky requirements, including UIN/registration, remote-pilot
          certification, and airspace-zone (Green/Yellow/Red) restrictions; and (c) for operations
          outside India, all equivalent civil-aviation, airspace, and remote-piloting regulations of
          the relevant jurisdiction.
        </p>
        <p>
          5.2. <strong className="text-white">Lawful-acquisition warranty.</strong> You represent and
          warrant that you have all necessary rights, licenses, permissions, and consents to capture,
          possess, upload, and process the imagery, including landowner permissions, survey
          authorizations, no-fly-zone clearances, and privacy clearances for any incidentally captured
          persons, vehicles, or private property.
        </p>
        <p>
          5.3. <strong className="text-white">Prohibited capture.</strong> You must not upload imagery
          captured over restricted, prohibited, defense, or sensitive installations, or in violation
          of any aviation, privacy, national-security, or surveying law.
        </p>
        <p>
          5.4. Any violation of this Section 5 is a material breach and triggers the indemnity in
          Section 12.
        </p>
      </Section>

      <Section heading="6. User Data Ownership and No-Training Commitment">
        <p>
          6.1. <strong className="text-white">Your data.</strong> As between you and Drisora, you
          retain all right, title, and interest in the imagery, video, geospatial data, project data,
          and other content you upload (&ldquo;User Data&rdquo;), and in outputs derived specifically
          from your User Data (&ldquo;User Outputs&rdquo;).
        </p>
        <p>
          6.2. <strong className="text-white">Limited license to operate.</strong> You grant Drisora
          a limited, non-exclusive, worldwide, royalty-free license to host, store, process, transmit,
          and display User Data solely to provide, maintain, secure, and support the Service for you.
          This license terminates when you delete the User Data or close your account, subject to
          Section 6.5 and our Privacy Policy.
        </p>
        <p>
          6.3. <strong className="text-white">No training without opt-in.</strong> Drisora will not
          use your User Data, User Outputs, or any uploaded imagery to train, fine-tune, or improve its
          machine-learning models or those of any third party,{" "}
          <strong className="text-white">unless you provide separate, explicit, opt-in consent</strong>.
          Opt-in is off by default, is granular, and may be withdrawn at any time (prospectively).
        </p>
        <p>6.4. We do not sell your User Data.</p>
        <p>
          6.5. <strong className="text-white">Aggregated / de-identified data.</strong> We may generate
          and use aggregated, anonymized, or irreversibly de-identified statistics that do not identify
          you, your Organization, or any specific location, for operational analytics and capacity
          planning. Such data is not training data and is not your User Data once irreversibly
          de-identified.
        </p>
      </Section>

      <Section heading="7. Open-Source Software Acknowledgment (AGPL-3.0)">
        <p>
          7.1. Portions of the Drisora backend incorporate or are derived from open-source software
          licensed under the <strong className="text-white">GNU Affero General Public License,
          Version 3.0 (AGPL-3.0)</strong>, including detection, segmentation, and depth-estimation
          model implementations (e.g., YOLO-family, SAM2, and Depth Anything V2 components, subject to
          their respective upstream licenses).
        </p>
        <p>
          7.2. The AGPL-3.0 governs only those open-source backend components and not your User Data,
          User Outputs, or the proprietary front-end, orchestration, and account layers of the Service.
        </p>
        <p>
          7.3. In accordance with AGPL-3.0 §13, the corresponding source code for the AGPL-licensed
          backend components, as deployed, is available at{" "}
          <a href="[SOURCE CODE / REPOSITORY URL]" className="text-[#F5A623]">
            [SOURCE CODE / REPOSITORY URL]
          </a>
          . Nothing in these Terms restricts any right you have under the AGPL-3.0 with respect to those
          components.
        </p>
        <p>
          7.4. Names and trademarks of upstream projects and model authors remain the property of their
          respective owners; their inclusion does not imply endorsement.
        </p>
      </Section>

      <Section heading="8. Acceptable Use Policy">
        <p>8.1. You agree not to:</p>
        <ul className="list-disc space-y-2 pl-6">
          <li>use the Service in violation of any applicable law, regulation, or third-party right;</li>
          <li>
            upload imagery acquired in breach of DGCA, aviation, privacy, survey, or
            national-security law (Section 5);
          </li>
          <li>
            upload malware, or attempt to disrupt, overload, reverse-engineer (except as permitted by
            the AGPL-3.0 or non-waivable law), or gain unauthorized access to the Service;
          </li>
          <li>
            misrepresent AI outputs as certified engineering assessments to any third party, regulator,
            or court;
          </li>
          <li>resell, sublicense, or provide the Service to third parties except as your plan permits;</li>
          <li>
            upload content that is unlawful, infringing, defamatory, or that contains personal data you
            have no lawful basis to process;
          </li>
          <li>use the Service to build a competing AI model or dataset; or</li>
          <li>circumvent usage limits, access controls, or security measures.</li>
        </ul>
        <p>
          8.2. We may suspend or terminate access for any violation, with or without notice where
          required to protect the Service, users, or the public.
        </p>
      </Section>

      <Section heading="9. Accounts and Security">
        <p>
          9.1. You are responsible for safeguarding your credentials and for all activity under your
          account. Notify us immediately at [SECURITY CONTACT EMAIL] of any unauthorized use.
        </p>
        <p>
          9.2. You are responsible for the accuracy of your registration information, including date of
          birth and professional-capacity confirmation.
        </p>
      </Section>

      <Section heading="10. Fees and Plans">
        <p>
          10.1. Paid features are billed per the plan you select, as set out at [PRICING URL] or your
          order form. Taxes (including GST) are your responsibility unless stated otherwise.
        </p>
        <p>10.2. We may modify pricing prospectively on [NOTICE PERIOD, e.g., 30 days&rsquo;] notice.</p>
      </Section>

      <Section heading="11. Disclaimers and Warranties">
        <p>
          11.1. THE SERVICE AND ALL OUTPUTS ARE PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS
          AVAILABLE&rdquo;, WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING IMPLIED
          WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, AND
          NON-INFRINGEMENT, to the maximum extent permitted by law.
        </p>
        <p>
          11.2. We do not warrant that the Service will be uninterrupted or error-free, or that AI
          outputs will be accurate, complete, or fit for any engineering, safety, or regulatory purpose.
        </p>
      </Section>

      <Section heading="12. Indemnification">
        <p>
          12.1. You agree to indemnify, defend, and hold harmless Drisora, its affiliates, officers,
          employees, and agents from any claims, damages, liabilities, penalties, costs, and expenses
          (including reasonable legal fees) arising out of or related to: (a) your User Data; (b) your
          unlawful or non-compliant acquisition of drone imagery (Section 5); (c) your violation of
          these Terms or any law; or (d) your reliance on or distribution of AI outputs.
        </p>
      </Section>

      <Section heading="13. Limitation of Liability">
        <p>
          13.1. TO THE MAXIMUM EXTENT PERMITTED BY LAW, DRISORA AND ITS AFFILIATES WILL NOT BE LIABLE
          FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, OR FOR
          LOSS OF PROFITS, REVENUE, DATA, GOODWILL, OR BUSINESS INTERRUPTION, EVEN IF ADVISED OF THE
          POSSIBILITY.
        </p>
        <p>
          13.2. <strong className="text-white">Aggregate liability cap.</strong> DRISORA&rsquo;S TOTAL
          AGGREGATE LIABILITY ARISING OUT OF OR RELATED TO THE SERVICE AND THESE TERMS WILL NOT EXCEED
          THE GREATER OF (A) THE TOTAL FEES YOU PAID TO DRISORA IN THE TWELVE (12) MONTHS IMMEDIATELY
          PRECEDING THE EVENT GIVING RISE TO THE CLAIM, OR (B) [INR 10,000 / USD 100].
        </p>
        <p>
          13.3. <strong className="text-white">Safety carve-out.</strong> Because the Service is
          advisory only (Section 4), Drisora is not liable for any decision, accident, structural
          failure, injury, death, property damage, or regulatory consequence resulting from reliance on
          AI outputs. Nothing in these Terms excludes liability that cannot be excluded under applicable
          law.
        </p>
      </Section>

      <Section heading="14. Term and Termination">
        <p>
          14.1. These Terms apply while you use the Service. You may stop using and delete your account
          at any time.
        </p>
        <p>
          14.2. We may suspend or terminate your access for breach, suspected unlawful use, or as
          required by law. Sections that by their nature should survive (including 4, 5, 6, 11, 12, 13,
          and 16) survive termination.
        </p>
      </Section>

      <Section heading="15. Changes to These Terms (Versioning)">
        <p>
          15.1. We may update these Terms from time to time. The version number and effective date at
          the top of this document identify the current version.
        </p>
        <p>
          15.2. For material changes, we will provide notice and, where required, request renewed
          acceptance before you continue to use the Service. Your continued use after the effective date
          of a non-material change constitutes acceptance.
        </p>
      </Section>

      <Section heading="16. Governing Law, Compliance, and EU Users">
        <p>
          16.1. <strong className="text-white">Governing law.</strong> These Terms are governed by the
          laws of India, including the Information Technology Act, 2000 and the Information Technology
          (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information)
          Rules, 2011 (&ldquo;SPDI Rules&rdquo;), and, as and when in force, the Digital Personal Data
          Protection Act, 2023. The courts at [CITY, e.g., Bengaluru], India have exclusive jurisdiction,
          subject to any non-waivable rights of consumers or data subjects.
        </p>
        <p>
          16.2. <strong className="text-white">GDPR (EU/EEA/UK users).</strong> Where the EU/UK General
          Data Protection Regulation applies to your use, our processing of personal data is governed by
          the GDPR provisions of our Privacy Policy, including lawful basis, data-subject rights, and
          international-transfer safeguards. Nothing in these Terms limits non-waivable rights you have
          under the GDPR.
        </p>
        <p>16.3. Contact: [CONTACT EMAIL]. Grievance Officer (India): [GRIEVANCE OFFICER NAME / EMAIL].</p>
      </Section>
    </LegalLayout>
  );
}
